basePath: /api
definitions:
  domain.Order:
    properties:
      cancellation_status:
        type: integer
      id:
        type: integer
      is_canceled:
        type: boolean
      order_rating:
        type: integer
      products:
        items:
          $ref: '#/definitions/domain.OrderProduct'
        type: array
      seller_id:
        type: integer
      status:
        type: integer
      total_order:
        type: number
      user_id:
        type: integer
    type: object
  domain.OrderProduct:
    properties:
      id:
        type: integer
      order_id:
        type: integer
      price:
        type: number
      product_id:
        type: string
      quantity:
        type: number
      total_price:
        type: number
    type: object
  dto.RequestInitialOrder:
    properties:
      products:
        $ref: '#/definitions/dto.RequestOrderProduct'
      seller_id:
        type: integer
    type: object
  dto.RequestOrderProduct:
    properties:
      price:
        type: number
      product_id:
        type: string
      quantity:
        type: number
    type: object
  dto.RequestRatingSeller:
    properties:
      rating:
        enum:
        - 1
        - 2
        - 3
        - 4
        - 5
        type: integer
    required:
    - rating
    type: object
  models.JSONResponsesSwaggerSucceed:
    properties:
      code:
        default: 200
        example: 200
        type: integer
      data:
        default: nil
        type: string
      status:
        default: Succeed
        example: Succeed
        type: string
    type: object
info:
  contact:
    email: fekalegi@gmail.com
    name: Feka Legi Heryana Rizki
  description: This is swagger for  Mini Rest Api
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Mini Rest Api
  version: "1.0"
paths:
  /order:
    get:
      consumes:
      - application/json
      description: This endpoint for fetch all order
      parameters:
      - in: query
        name: page_number
        type: integer
      - in: query
        name: page_size
        type: integer
      - in: query
        name: status
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            allOf:
            - $ref: '#/definitions/models.JSONResponsesSwaggerSucceed'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/domain.Order'
                  type: array
              type: object
      summary: Fetch All Order
      tags:
      - Order
    post:
      consumes:
      - application/json
      description: This endpoint for CreateInitialOrder
      parameters:
      - description: Create new order
        in: body
        name: services
        required: true
        schema:
          $ref: '#/definitions/dto.RequestInitialOrder'
      - description: ID Order
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.JSONResponsesSwaggerSucceed'
      summary: CreateInitialOrder New Order
      tags:
      - Order
  /order/{id}:
    delete:
      consumes:
      - application/json
      description: This endpoint for Delete order
      parameters:
      - description: Order Id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            allOf:
            - $ref: '#/definitions/models.JSONResponsesSwaggerSucceed'
            - properties:
                data:
                  $ref: '#/definitions/domain.Order'
              type: object
      summary: Delete Order by ID
      tags:
      - Order
    get:
      consumes:
      - application/json
      description: This endpoint for fetch order by ID
      parameters:
      - description: Order Id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            allOf:
            - $ref: '#/definitions/models.JSONResponsesSwaggerSucceed'
            - properties:
                data:
                  $ref: '#/definitions/domain.Order'
              type: object
      summary: Fetch Order by ID
      tags:
      - Order
  /order/{id}/arrived:
    patch:
      consumes:
      - application/json
      description: This endpoint for UpdateStatusOrderToArrived
      parameters:
      - description: ID Order
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.JSONResponsesSwaggerSucceed'
      summary: UpdateStatusOrderToArrived
      tags:
      - Order
  /order/{id}/finished:
    patch:
      consumes:
      - application/json
      description: This endpoint for UpdateStatusOrderToFinished
      parameters:
      - description: ID Order
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.JSONResponsesSwaggerSucceed'
      summary: UpdateStatusOrderToFinished
      tags:
      - Order
  /order/{id}/pack:
    patch:
      consumes:
      - application/json
      description: This endpoint for UpdateStatusOrderToPacking
      parameters:
      - description: ID Order
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.JSONResponsesSwaggerSucceed'
      summary: UpdateStatusOrderToPacking
      tags:
      - Order
  /order/{id}/pay:
    patch:
      consumes:
      - application/json
      description: This endpoint for UpdateStatusOrderToPayment
      parameters:
      - description: ID Order
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.JSONResponsesSwaggerSucceed'
      summary: UpdateStatusOrderToPayment
      tags:
      - Order
  /order/{id}/products:
    post:
      consumes:
      - application/json
      description: This endpoint for AddOrUpdateOrderProducts
      parameters:
      - description: Add or Update Order Product
        in: body
        name: services
        required: true
        schema:
          $ref: '#/definitions/dto.RequestOrderProduct'
      - description: ID Order
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.JSONResponsesSwaggerSucceed'
      summary: AddOrUpdateOrderProducts New Order
      tags:
      - Order
  /order/{id}/rating:
    post:
      consumes:
      - application/json
      description: This endpoint for AddRatingSeller
      parameters:
      - description: Request Rating
        in: body
        name: services
        required: true
        schema:
          $ref: '#/definitions/dto.RequestRatingSeller'
      - description: ID Order
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.JSONResponsesSwaggerSucceed'
      summary: AddRatingSeller
      tags:
      - Order
  /order/{id}/shipped:
    patch:
      consumes:
      - application/json
      description: This endpoint for UpdateStatusOrderToShipped
      parameters:
      - description: ID Order
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.JSONResponsesSwaggerSucceed'
      summary: UpdateStatusOrderToShipped
      tags:
      - Order
  /order/product/{id}:
    delete:
      consumes:
      - application/json
      description: This endpoint for Delete order Product
      parameters:
      - description: Order Product ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            allOf:
            - $ref: '#/definitions/models.JSONResponsesSwaggerSucceed'
            - properties:
                data:
                  $ref: '#/definitions/domain.Order'
              type: object
      summary: Delete Order Product by ID
      tags:
      - Order
  /order/seller/{id}:
    get:
      consumes:
      - application/json
      description: This endpoint for fetch order by ID
      parameters:
      - description: Order Id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            allOf:
            - $ref: '#/definitions/models.JSONResponsesSwaggerSucceed'
            - properties:
                data:
                  $ref: '#/definitions/domain.Order'
              type: object
      summary: FetchRatingSeller by ID
      tags:
      - Order
swagger: "2.0"
